const chatQuestions = [
  'Great, so let\'s get started from the beginning - with nouns.',
  'Norwegian nouns have three genders: masculine, feminine and neuter (neutral).',
  'The indefinite articles are en (masculine), ei (feminine) and et (neuter). Similar to English, but indefinite articles in English are a or an.',
  'Yep, sure: feminine: ei jente (a girl), masculine: en gutt (a boy), and neuter: et hus  (a house). Do you remember how to form a definite noun?',
  'Well, in Norwegian, you need to form a definite noun by adding -en at the end of masculine words, -a at the end of feminine words and –et at the end of neuter words.',
  'So, how to form a definite form from “ei jenta” which an indefinite noun? : jenta, jenten or jentet?',
  'Great, you are adding -a at the end of feminine words, so jenta is the correct form. Let\'s continue, shall we?',
  'The definite form of the masculine word "en gutt" (a boy)   is "gutten" (the boy) and the definite form of the neuter   word "et hus" (a house) is "huset" (the house). Clear?',
  'Let\'s go to the plural then. Do you remember how to create a plural word?',
  'The plural of indefinite nouns is normally formed by adding – er: ei jenta - jenter, en gutt - gutter, et synspunkt (a point of view) - synspunktet. Sound simple?',
  'But there is one exception: short one syllable et-words have no ending in the indefinite plural form: et hus - hus, et barn (a child) - barn.',
  'Do you remember how to form the definite form of the plural?',
  'Yes, great, for example: “biler” (cars) - “bilene” (the cars); jenter - jentene, aviser - avisene. So a definite plural from the noun en gutt is guttene.',
  'Nicely done! Ok, so let’s move on; it\'s adjective time!',
  'That\'s the spirit! :) The main rule is that most adjectives add – t to the neuter and – e to the plural. You can see what it looks like in the example below:',
  'en varm dag (a warm day) - ei varm seng (a warm bed) - et varmt hus (a warm house) - varme dager (warm days) - varme senger (warm beds) - varme huser (warm houses). Easy-peasy, right?',
  'Good! There are a few exceptions from this main rule, but let\'s leave this for another time. I want to show you one simple, but important and useful exception: the word small - "liten" in Norwegian looks like this: en liten dag - ei lita seng - et lite hus - små dager - små senger - små huser',
  'How nice! So far we have learned how to place adjectives in front of a noun in the indefinite form. However, adjectives can also describe nouns in a definite form.',
  'Then the adjectives end in –e (just like the plural form). In addition, the adjectives require the definite articles: den, det and de which agree in gender and number with the noun: den + varme+ dagen = den varme dagen.',
  'den varme dagen - den varme senga - det varme huset - de varme dagene - de varme sengene - de varme husene. It\’s not difficult, yeah?',
  'There is one small, little thing I want to tell you before we end ok?',
  'The irregular form of liten (small) looks like that\
  den lille dagen en lille senga det lille huset de små dagene  de små sengene  de små husene.',
];
const chatButtonsLeft = [
  'Ok, let\'s go then!',
  'Sounds simple!',
  'Can you give me an example?',
  'Actually, I would like to refresh this topic.',
  'Sounds simple.',
  'jenta',
  'Yes, please :)',
  'Crystal clear!',
  'I am not sure.',
  'Easy as winking!',
  'Oh yeah!',
  'You need to add to the end of the noun -ene.',
  'I thought so.',
  'Yeah, I can\'t wait!',
  'Ok, let\'s see examples!',
  'Surely!',
  'Thanks, you are the best, Mila!',
  'In a definite form? Interesting...',
  'I need an example',
  'Not at all.',
  'I\'m all ears.',
  'Thanks, Mila, now I know everything about nouns and adjectives!'
];
const chatButtonsRight = [
  'Yeah, I can’t wait!',
  'Ok, and?',
  'An example will be handy.',
  'Nope, I need help :)',
  'Sounds complicated.',
  'jenta',
  'Why not?',
  'Clear as a day!',
  'Kind of :)',
  'Easy as pie!',
  'Steel easy.',
  'By adding -ene to the end?',
  'I knew it!',
  'I am so excited!',
  'An example, please!',
  'Easy as ABC!',
  'Wow, thanks Mila!',
  'Give me more!',
  'Example, please!',
  'I am still waiting for the difficult part.',
  'Yes, please!',
  'Mila, you are an amazing teacher!'
]
